### ISSUE TITLE
Can't import preprocess

### ISSUE THREAD

**Issue by giangdip2410** [baokhanh92/OCR-Vietnamese-Cinnamon-Challenge#1]

**Comment by baokhanh92** [comment]
Hi Giang, the problem could be because the wrong naming, try to change preprocess to preprocess_first as the above function, or cancel out all the line with preprocess. Since it's just for checking image size, not really affect the end result.
![image](https://user-images.githubusercontent.com/57140682/81385663-f2289580-913d-11ea-8ce8-79da737c6198.png)

**Comment by giangdip2410** [comment]
It is great for me, thank you very much for your kindly and clearly explanation .
